name: tayninh_tour_mobile
description: "HDV Tour Management Mobile App - Ứng dụng quản lý tour cho Hướng dẫn viên"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296

  # State Management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.6.2

  # HTTP & API
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0

  # Storage & Security
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3

  # QR Code & Camera
  mobile_scanner: ^5.0.4
  image_picker: ^1.1.2
  permission_handler: ^11.3.1

  # UI Components
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  # Utils
  intl: ^0.19.0
  logger: ^2.4.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  retrofit_generator: ^8.2.1
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
